### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by adammaj1** [fredrik-johansson/arbcmath#2]
a@zelman:~/arbcmath$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
a@zelman:~/arbcmath$ gcc example.c -larb -lflint -lgmp -lmpfr  -lpthread -Wall
In file included from example.c:1:0:
arbcmath.h: In function ‘_acb_init_set_c’:
arbcmath.h:21:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }

**Comment by fredrik-johansson** [comment]
Right, the return type should have been declared as void. Fixed.
