### ISSUE TITLE
Preferred citation?

### ISSUE THREAD

**Issue by miyamot0** [fredrik-johansson/arbcmath#3]
Greetings, I'm interested in using your 2f1 methods in an academic publication. I see you released everything in the public domain (which I'm very grateful for), but I'm curious if you have any additional information you might like included (i.e., citation). Is this something that's been published in any journals or proceedings?

Thanks again for this.

SG

**Comment by fredrik-johansson** [comment]
The preferred citation for Arb is listed here: http://arblib.org/credits.html#citing-arb

Specifically concerning the implementation of the 2F1 function, there is also this preprint: https://arxiv.org/abs/1606.06977

**Comment by miyamot0** [comment]
Excellent. Many thanks.
